version: "3.9"

services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
